#!/usr/bin/env python3
"""Run, render and check the Flash-Next README performance tables and graph.

The README section between the `flash-next-performance` markers and
`docs/images/flash-next-performance.svg` are generated only from the `ninfer_bench` JSON reports in
`docs/data/flash-next-performance/`. One report covers one variant, decode mode and context group.

  run     measure the matrix with ninfer_bench and store the reports
  render  write the README section and the SVG from the stored reports
  check   regenerate both in memory and fail if the committed files differ
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
import xml.etree.ElementTree as ElementTree

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs/data/flash-next-performance"
SVG = ROOT / "docs/images/flash-next-performance.svg"
README = ROOT / "README.md"
BEGIN = "<!-- flash-next-performance:begin (generated by tools/bench/flash_next_readme.py) -->"
END = "<!-- flash-next-performance:end -->"
CORPUS = "bench/fixtures/qwen3_8_flash_next_context.ids"

VARIANTS = {
    "16-bit": "out/v3/swift_1_5_qwen3_8_flash_next_nvfp4.ninfer",
    "8-bit": "out/v3/swift_1_5_qwen3_8_flash_next_nvfp4_fp8ple_fp8proj.ninfer",
}
MODES = {
    "No speculative decoding": [],
    "MTP3": ["--spec", "mtp", "--draft-tokens", "3"],
    "MTP3 + lm-head-draft": ["--spec", "mtp", "--draft-tokens", "3", "--lm-head-draft"],
}
# Context groups keep each KV allocation close to its prompts, as one request would size it.
GROUPS = {
    "short": ("512,256;8192,256", 9216),
    "long": ("65536,256;131072,256", 131584),
    "max": ("261632,256", 262144),
}
CONTEXTS = [(512, "512"), (8192, "8K"), (65536, "64K"), (131072, "128K"),
            (261632, "256K (maximum)")]
COLORS = {"No speculative decoding": "#4e79a7", "MTP3": "#f28e2b",
          "MTP3 + lm-head-draft": "#59a14f"}


def slug(text: str) -> str:
    return text.lower().replace(" + ", "-").replace(" ", "-")


def report_path(variant: str, mode: str, group: str) -> Path:
    return DATA / f"{slug(variant)}-{slug(mode)}-{group}.json"


def run(args: argparse.Namespace) -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    for variant, weights in VARIANTS.items():
        for mode, flags in MODES.items():
            for group, (pairs, max_context) in GROUPS.items():
                out = report_path(variant, mode, group)
                command = [str(args.bench), "--weights", weights, "--corpus", CORPUS, "-pg", pairs,
                           "--max-ctx", str(max_context), "--prefill-chunk", "8192",
                           "--kv-dtype", "bf16", *flags, "--warmup", "1", "-r", "2", "-o", "json",
                           "--output-file", str(out)]
                print(f"{variant} / {mode} / {group}", flush=True)
                subprocess.run(command, cwd=ROOT, check=True, stdout=subprocess.DEVNULL)


def load() -> dict[tuple[str, str], dict[int, tuple[float, int]]]:
    """Return (variant, mode) -> prompt length -> (decode tok/s, prefill tok/s), as published."""
    data: dict[tuple[str, str], dict[int, tuple[float, int]]] = {}
    for variant, weights in VARIANTS.items():
        for mode, flags in MODES.items():
            rows: dict[int, tuple[float, int]] = {}
            for group, (pairs, max_context) in GROUPS.items():
                path = report_path(variant, mode, group)
                report = json.loads(path.read_text())
                command = report["command"]
                if (report.get("artifact_type") != "ninfer_bench_report" or
                        not report["artifact"]["path"].endswith(Path(weights).name) or
                        "--kv-dtype bf16" not in command or
                        f"--max-ctx {max_context} " not in command or
                        ("--lm-head-draft" in flags) != ("--lm-head-draft" in command) or
                        ("--spec" in flags) != ("--spec mtp" in command)):
                    raise SystemExit(f"{path}: report does not match {variant} / {mode} / {group}")
                for test in report["tests"]:
                    rows[test["n_prompt"]] = (round(test["decode_output_tok_s_mean"], 1),
                                              round(test["prefill_tok_s_mean"]))
            if sorted(rows) != [length for length, _ in CONTEXTS]:
                raise SystemExit(f"{variant} / {mode}: prompt lengths {sorted(rows)}")
            data[variant, mode] = rows
    return data


def change(old: float, new: float) -> str:
    return f"{(new / old - 1) * 100:+.0f}%"


def readme_section(data) -> str:
    lines = ["### Decode", ""]
    titles = {"No speculative decoding": "Without speculative decoding:", "MTP3": "MTP3:",
              "MTP3 + lm-head-draft": "MTP3 with `--lm-head-draft`:"}
    for mode in MODES:
        lines += [titles[mode], "", "| Context | 16-bit | 8-bit | Change |", "|---:|---:|---:|---:|"]
        for length, label in CONTEXTS:
            old, new = data["16-bit", mode][length][0], data["8-bit", mode][length][0]
            lines.append(f"| {label} | {old:.1f} tok/s | {new:.1f} tok/s | {change(old, new)} |")
        lines.append("")
    slowdowns = [1 - data[variant, mode][length][1] / data[variant, "No speculative decoding"][length][1]
                 for variant in VARIANTS for mode in list(MODES)[1:] for length, _ in CONTEXTS]
    lines += ["### Prefill", "",
              "The prompt is also processed by the MTP layer, so MTP3 makes prefill "
              f"{min(slowdowns) * 100:.0f}% to {max(slowdowns) * 100:.0f}% slower.", ""]
    short = {"No speculative decoding": "No MTP", "MTP3": "MTP3", "MTP3 + lm-head-draft": "MTP3 + head"}
    header = [f"{short[mode]}, {variant}" for mode in MODES for variant in VARIANTS]
    lines += ["| Prompt length | " + " | ".join(header) + " |", "|---:|" + "---:|" * len(header)]
    for length, label in CONTEXTS:
        cells = [f"{data[variant, mode][length][1]:,}" for mode in MODES for variant in VARIANTS]
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def svg(data) -> str:
    width, height, panel_w, panel_h, top = 1100, 520, 440, 330, 90
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
           f'viewBox="0 0 {width} {height}" font-family="Helvetica, Arial, sans-serif">',
           f'<rect width="{width}" height="{height}" fill="#ffffff"/>']

    def text(x, y, s, size=13, anchor="start", weight="normal", color="#222"):
        out.append(f'<text x="{x:.1f}" y="{y:.1f}" font-size="{size}" text-anchor="{anchor}" '
                   f'font-weight="{weight}" fill="{color}">{s}</text>')

    def panel(left, title, column, ymax, ystep):
        y0 = top + panel_h
        xs = [left + 30 + i * (panel_w - 60) / (len(CONTEXTS) - 1) for i in range(len(CONTEXTS))]
        sy = lambda v: y0 - v / ymax * panel_h
        text(left + panel_w / 2, top - 16, title, 16, "middle", "bold")
        for v in range(0, ymax + 1, ystep):
            out.append(f'<line x1="{left}" y1="{sy(v):.1f}" x2="{left + panel_w}" y2="{sy(v):.1f}" '
                       f'stroke="#e3e3e3" stroke-width="1"/>')
            text(left - 8, sy(v) + 4, f"{v:,}", 12, "end", color="#555")
        out.append(f'<line x1="{left}" y1="{y0}" x2="{left + panel_w}" y2="{y0}" stroke="#888"/>')
        out.append(f'<line x1="{left}" y1="{top}" x2="{left}" y2="{y0}" stroke="#888"/>')
        for x, (_, label) in zip(xs, CONTEXTS):
            text(x, y0 + 20, label.split(" ")[0], 12, "middle", color="#555")
        text(left + panel_w / 2, y0 + 42, "Context length (tokens)", 13, "middle", color="#333")
        out.append(f'<text transform="translate({left - 58},{top + panel_h / 2}) rotate(-90)" '
                   f'font-size="13" text-anchor="middle" fill="#333">Tokens per second</text>')
        for (variant, mode), rows in data.items():
            values = [rows[length][column] for length, _ in CONTEXTS]
            if max(values) > ymax:
                raise SystemExit(f"{title}: {variant} / {mode} exceeds the {ymax} axis")
            color = COLORS[mode]
            dash = "" if variant == "8-bit" else ' stroke-dasharray="7,5"'
            points = " ".join(f"{x:.1f},{sy(v):.1f}" for x, v in zip(xs, values))
            out.append(f'<polyline data-series="{variant} / {mode}" points="{points}" fill="none" '
                       f'stroke="{color}" stroke-width="2.5"{dash}/>')
            for x, v in zip(xs, values):
                fill = color if variant == "8-bit" else "#fff"
                out.append(f'<circle cx="{x:.1f}" cy="{sy(v):.1f}" r="4" fill="{fill}" '
                           f'stroke="{color}" stroke-width="2"/>')

    text(width / 2, 32, "Qwen3.8 Flash-Next (Swift 1.5) on RTX PRO 6000, 600 W, one request", 18,
         "middle", "bold")
    text(width / 2, 54, "Solid: 8-bit variant. Dashed: 16-bit variant.", 13, "middle", color="#444")
    panel(80, "Decode (tg)", 0, 450, 50)
    panel(620, "Prefill (pp)", 1, 16000, 2000)
    x, y = 230, top + panel_h + 72
    for mode, color in COLORS.items():
        out.append(f'<line x1="{x}" y1="{y}" x2="{x + 28}" y2="{y}" stroke="{color}" stroke-width="3"/>')
        text(x + 36, y + 4, mode, 13)
        x += 60 + len(mode) * 7.2
    out.append("</svg>")
    return "\n".join(out) + "\n"


def with_section(readme: str, section: str) -> str:
    begin, end = readme.find(BEGIN), readme.find(END)
    if begin < 0 or end < begin or readme.count(BEGIN) != 1 or readme.count(END) != 1:
        raise SystemExit("README.md needs exactly one flash-next-performance marker pair")
    return readme[:begin + len(BEGIN)] + "\n" + section + "\n" + readme[end:]


def check_svg_points(image: str, data) -> None:
    """Read every plotted point back from the SVG and compare it with the reports."""
    namespace = {"svg": "http://www.w3.org/2000/svg"}
    lines = ElementTree.fromstring(image).findall("svg:polyline", namespace)
    if len(lines) != 2 * len(data):
        raise SystemExit(f"SVG has {len(lines)} series, expected {2 * len(data)}")
    for index, line in enumerate(lines):
        column, ymax = (0, 450) if index < len(data) else (1, 16000)
        variant, mode = line.get("data-series").split(" / ")
        plotted = [(420 - float(point.split(",")[1])) / 330 * ymax
                   for point in line.get("points").split()]
        expected = [data[variant, mode][length][column] for length, _ in CONTEXTS]
        # Coordinates carry one decimal over 330 px, so a point resolves to ymax / 6600.
        if any(abs(p - e) > ymax / 6600 for p, e in zip(plotted, expected)):
            raise SystemExit(f"SVG {variant} / {mode} points {plotted} != {expected}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=("run", "render", "check"))
    parser.add_argument("--bench", type=Path, default=ROOT / "build/bench/ninfer_bench")
    args = parser.parse_args()
    if args.command == "run":
        run(args)
        return
    data = load()
    image = svg(data)
    readme = with_section(README.read_text(), readme_section(data))
    check_svg_points(image, data)
    if args.command == "render":
        SVG.write_text(image)
        README.write_text(readme)
        print(f"wrote {SVG.relative_to(ROOT)} and the README section")
        return
    stale = [path.name for path, text in ((SVG, image), (README, readme)) if path.read_text() != text]
    if stale:
        sys.exit("out of date with docs/data/flash-next-performance: " + ", ".join(stale))
    print("README tables and SVG match the benchmark reports")


if __name__ == "__main__":
    main()
